# Gopkg.toml for github.com/ulule/loukoum

ignored = [
  "github.com/stretchr/testify/require",
  "github.com/davecgh/go-spew",
  "github.com/lib/pq",
  "github.com/jmoiron/sqlx"
]

[metadata]
  codename = "loukoum"

[prune]
  unused-packages = true
  non-go = true
  go-tests = true

[[constraint]]
  name = "github.com/pkg/errors"
  version = "0.8.0"
